### ISSUE TITLE
Declaring a and b for the bool segment

### ISSUE THREAD

**Issue by bhtran** [learn-co-curriculum/objc-simple-math#3]
In this section: "Write a series of three BOOLs to compare the variables a and b from Code-Along A. Use the is-equal-to comparator (==), the greater-than comparator (>), and the less-than comparator (<). You can call the variables aIsEqualToB, aIsGreaterThanB, and aIsLessThanB respectively:
BOOL aIsEqualToB = a == b;
BOOL aIsGreaterThanB = a > b;
BOOL aIsLessThanB = a < b;
Then print each BOOL in a series of NSLog()s:

NSLog(@"a == b: %d", aIsEqualToB);
NSLog(@"a > b: %d", aIsGreaterThanB);
NSLog(@"a < b: %d", aIsLessThanB);
This should print:

a == b: 0
a > b: 0
a < b: 1
"

I noticed that Xcode failed to run when I enter the BOOL statements without declaring what A and B is. So I declared:

NSInteger a = 0;
NSInteger b = 1;

in order to make the following true:

a == b: 0
a > b: 0
a < b: 1

**Comment by markedwardmurray** [comment]
Right, those should have been declared earlier in Code-Along A:

_Write a series of three BOOLs to compare the variables a and b from Code-Along A._

**Comment by bhtran** [comment]
thank you for clarifying!
